### ISSUE TITLE
请问可以发布测试数据集的格式吗？

### ISSUE THREAD

**Issue by zuzi2015** [sunsmarterjie/SDL-Skeleton#17]
我在运行的时候报了错：
Traceback (most recent call last):
  File "test_RN.py", line 46, in <module>
    inp, fname, H, W = dataloader[idx]
IndexError: list index out of range
 或者是：
IsADirectoryError: [Errno 21] Is a directory: './OriginalSKLARGE/images/test'

**Comment by Sakura1237** [comment]
> 



> 我在运行的时候报错了： Traceback (most recent call last): File "test_RN.py", line 46, inp , fname, H, W = dataloader[idx] IndexError: list index out of range 或者是： IsADirectoryError: [Errno 21] 是一个目录：'./OriginalSKLARGE/images/test'

您好，您现在有测试数据集了吗
